/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import pdf.GeraOficioxxxx;
import pdf.Oficio;

/**
 *
 * @author f7057419
 */
public final class FrmPrincipalTeste extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrmPrincipalTeste() throws IOException, Exception {
        Integer mes;
        String mesExtenso = null;

        //Para o form ficar no meio da tela    
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        Integer largura;
        Integer altura;

        largura = d.width;
        largura = (largura / 2) - (740 / 2);
        altura = d.height;
        altura = (altura / 2) - (920 / 2);

        initComponents();

        setBounds(largura, altura, 727, 920);
        Color corDoformulario = new Color(240, 240, 240);
        getContentPane().setBackground(corDoformulario);

        LocalDate hoje = new LocalDate();//hoje

        //tratamento mês por extenso
        mes = hoje.getMonthOfYear();

        switch (mes) {
            case 1:
                mesExtenso = "Janeiro";
                break;
            case 2:
                mesExtenso = "Fevereiro";
                break;
            case 3:
                mesExtenso = "Março";
                break;
            case 4:
                mesExtenso = "Abril";
                break;
            case 5:
                mesExtenso = "Maio";
                break;
            case 6:
                mesExtenso = "Junho";
                break;
            case 7:
                mesExtenso = "Julho";
                break;
            case 8:
                mesExtenso = "Agosto";
                break;
            case 9:
                mesExtenso = "Setembro";
                break;
            case 10:
                mesExtenso = "Outubro";
                break;
            case 11:
                mesExtenso = "Novembro";
                break;
            case 12:
                mesExtenso = "Dezembro";
                break;
        }
        txtData.setText("São Paulo, " + hoje.getDayOfMonth() + " de " + mesExtenso + " de " + hoje.getYear());
        fecharMeiaNoite();

       // Copiar arquivos de logo LogoRetangular.png e AR.pdf da rede para temp
        //File arIN = new File("c:/temp/AR.pdf");  
        File arIN = new File("\\\\Srispo02525\\cso1981servjudfunci$\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\AR.pdf");
   //     \\Srispo02525\cso1981servjudfunci$\Publica\INFORMACOES A TERCEIROS\OFÍCIO\OFICIO_PROG

        File arOUT = new File("c:/temp/AR.pdf");
        copyFile(arIN, arOUT);

        // File logoIN = new File("c:/temp/LogoRetangular.png");  
        File logoIN = new File("\\\\Srispo02525\\cso1981servjudfunci$\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\LogoRetangular.png");

        File logoOUT = new File("c:/temp/LogoRetangular.png");
        copyFile(logoIN, logoOUT);

    }

    public void copyFile(File in, File out) throws Exception {
        FileChannel destinationChannel;
        try (FileChannel sourceChannel = new FileInputStream(in).getChannel()) {
            destinationChannel = new FileOutputStream(out).getChannel();
            sourceChannel.transferTo(0, sourceChannel.size(), destinationChannel);
        }
        destinationChannel.close();
    }

    public void fecharMeiaNoite() {
        new Thread() {
            @Override
            public void run() {

                DateTime dateTime1 = new DateTime();
                //     System.out.println(dateTime1.getMinuteOfDay());

                int dateTime3 = dateTime1.getDayOfMonth();
                dateTime3 = dateTime3 + 1;
                System.out.println(dateTime3);

                int dateTime4 = 0;
                while (dateTime3 != dateTime4) {
                    dateTime4 = dateTime1.getDayOfMonth();
                }
                System.exit(0);

            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAbc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnOficio = new javax.swing.JButton();
        btnAR = new javax.swing.JButton();
        btnLimpar = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCorpo = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextPane();
        txtOficio = new javax.swing.JTextField();
        txtAOF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProcesso = new javax.swing.JTextField();
        txtEnvolvido = new javax.swing.JTextField();
        txtOficioN = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtReu = new javax.swing.JTextField();
        txtDestinatário = new javax.swing.JTextField();
        txtInquerito1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLinhas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/nome2.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 745, 70);

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Endereço:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 570, 110, 26);

        txtData.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txtData.setText("São Paulo, 22 de xxxxx de xxxx");
        txtData.setToolTipText("");
        getContentPane().add(txtData);
        txtData.setBounds(10, 76, 310, 20);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("AOF : ");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 129, 40, 14);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Desenvolvido por: F7057419 Mautício da Silva Luiz");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 870, 270, 17);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 210, 697, 2);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("OFICIO CENOP SJ N.º : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 108, 160, 17);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel15.setText("_______________________________________________________________________________________");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 810, 710, 17);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        jLabel16.setText("CENOP- Serviçõs Judiciais São Paulo/SP");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 830, 210, 17);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("BANCO BRASIL S.A.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(270, 553, 140, 17);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jLabel18.setText("CENOP SERVIÇOS SÃO PAULO/SP");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(240, 570, 200, 17);

        jLabel19.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("Resposta:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 220, 140, 26);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Digite as iniciaios do seu nome:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 230, 210, 16);

        txtAbc.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtAbc.setForeground(new java.awt.Color(51, 51, 255));
        txtAbc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbc.setText("aaa");
        txtAbc.setToolTipText("");
        txtAbc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbcActionPerformed(evt);
            }
        });
        getContentPane().add(txtAbc);
        txtAbc.setBounds(650, 230, 60, 18);

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jLabel20.setText("Rua Líbero Badaró,568 - 17º Andar -CEP 01008-000 São Paulo/SP");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(180, 850, 350, 17);

        btnOficio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOficio.setText("OFICIO");
        btnOficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficioActionPerformed(evt);
            }
        });
        getContentPane().add(btnOficio);
        btnOficio.setBounds(10, 760, 150, 30);

        btnAR.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAR.setText("AR");
        btnAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnARActionPerformed(evt);
            }
        });
        getContentPane().add(btnAR);
        btnAR.setBounds(170, 760, 140, 30);

        btnLimpar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(600, 760, 105, 30);

        txtCorpo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCorpo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCorpo.setText("Meritíssimo Juiz, \n\n\tEm atendimento à requisição de Vossa Excelência, por meio do ofício expedido nos autos do processo em epígrafe, informamos que Agnaldo Terra Rocha, CPF 247.687.258-05, não possui cartão de crédito VISA ou MASTERCARD nesta instituição. \nAs informações contidas neste ofício são confidenciais e estão sendo encaminhadas à Autoridade competente e requisitante com o devido amparo da Lei Complementar nº 105, de 10 de janeiro de 2001, que dispõe sobre o sigilo das operações e serviços prestados pelas Instituições Financeiras.\nColocamo-nos à disposição para eventuais  esclarecimentos e informações porventura necessários, aproveitando o ensejo para enviar protestos de elevada estima e consideração.\n\nRespeitosamente,\n");
        jScrollPane3.setViewportView(txtCorpo);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 250, 700, 300);

        txtEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEndereco.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtEndereco.setText("Trazibulo José Ferreira da Silva\nTribunal de Justiça do Estado de São Paulo \n1ª Vara da Família e das Sucessões – Comarca de Itapetininga \nRua Carlos Cardoso, s/n – Jardim Mesquita\nCEP 18213-540 – Itapetininga/SP\n");
        jScrollPane4.setViewportView(txtEndereco);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 640, 700, 110);

        txtOficio.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtOficio.setText("2014/14551687");
        txtOficio.setToolTipText("");
        txtOficio.setBorder(null);
        getContentPane().add(txtOficio);
        txtOficio.setBounds(170, 108, 200, 15);

        txtAOF.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtAOF.setText("2014/10120");
        txtAOF.setToolTipText("");
        txtAOF.setBorder(null);
        txtAOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAOFActionPerformed(evt);
            }
        });
        getContentPane().add(txtAOF);
        txtAOF.setBounds(170, 129, 200, 15);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setText("Processo Nº :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 90, 15);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setText("Inquerito Policial Nº :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 140, 15);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setText("Ofício Nº : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 120, 70, 15);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setText("Autor :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 140, 50, 15);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setText("Réu :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 160, 40, 15);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setText("Envolvido :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 180, 80, 15);

        txtProcesso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtProcesso.setText("0004853-70.2013.8.26.0269");
        txtProcesso.setToolTipText("");
        txtProcesso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtProcesso);
        txtProcesso.setBounds(170, 160, 200, 15);

        txtEnvolvido.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtEnvolvido.setToolTipText("");
        txtEnvolvido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEnvolvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnvolvidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnvolvido);
        txtEnvolvido.setBounds(500, 180, 200, 15);

        txtOficioN.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtOficioN.setToolTipText("");
        txtOficioN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtOficioN);
        txtOficioN.setBounds(500, 120, 200, 15);

        txtAutor.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtAutor.setText("Agnaldo Terra Rocha");
        txtAutor.setToolTipText("");
        txtAutor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAutor);
        txtAutor.setBounds(500, 140, 200, 15);

        txtReu.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtReu.setText("Paloma Martins Rocha e outros");
        txtReu.setToolTipText("");
        txtReu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtReu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReuActionPerformed(evt);
            }
        });
        getContentPane().add(txtReu);
        txtReu.setBounds(500, 160, 200, 15);

        txtDestinatário.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtDestinatário.setText("Ao Excelentíssimo Dr.: ");
        txtDestinatário.setToolTipText("");
        txtDestinatário.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDestinatário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinatárioActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestinatário);
        txtDestinatário.setBounds(10, 605, 220, 20);

        txtInquerito1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtInquerito1.setToolTipText("");
        txtInquerito1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtInquerito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInquerito1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtInquerito1);
        txtInquerito1.setBounds(170, 180, 200, 15);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel9.setText("Inserir linhas:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 560, 100, 15);

        txtLinhas.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtLinhas.setText("0");
        txtLinhas.setToolTipText("");
        txtLinhas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinhasActionPerformed(evt);
            }
        });
        getContentPane().add(txtLinhas);
        txtLinhas.setBounds(680, 560, 30, 20);

        jPanel1.setBackground(new java.awt.Color(0, 96, 168));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 370, 50);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Teste");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 80, 50, 20);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Teste");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(430, 80, 50, 20);

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Teste");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(480, 80, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbcActionPerformed

    private void btnOficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficioActionPerformed
        // TODO add your handling code here:
        //    GeraOficioxxxx G = new GeraOficioxxxx();

        Oficio oficio = new Oficio();

       try {
            oficio.setLinhas(Integer.parseInt(txtLinhas.getText()));
        } catch (Exception e) {
            oficio.setLinhas(1);
        }
        try {
            oficio.setOficio(txtOficio.getText());
        } catch (Exception e) {
            oficio.setOficio("");
        }
        try {
//            oficio.setAof(txtAOF.getText());
        } catch (Exception e) {
  //          oficio.setAof("");
        }
        try {
            oficio.setOficio(txtOficio.getText());
        } catch (Exception e) {
            oficio.setOficio("");
        }
        try {
            oficio.setProcesso(txtProcesso.getText());
        } catch (Exception e) {
            oficio.setProcesso("");
        }
        try {
            oficio.setCorpo(txtCorpo.getText());
        } catch (Exception e) {
            oficio.setCorpo("");
        }
        try {
            oficio.setDestinario(txtDestinatário.getText());
        } catch (Exception e) {
            oficio.setDestinario("");
        }
        try {
            oficio.setEndereco(txtEndereco.getText());
        } catch (Exception e) {
            oficio.setEndereco("");
        }
        try {
//            oficio.setInquerito(txtInquerito1.getText());
        } catch (Exception e) {
  //          oficio.setInquerito("");
        }
        try {
    //        oficio.setOficion(txtOficioN.getText());
        } catch (Exception e) {
      //      oficio.setOficion("");
        }
        try {
       //     oficio.setAutor(txtAutor.getText());
        } catch (Exception e) {
        //    oficio.setAutor("");
        }
        try {
            oficio.setReu(txtReu.getText());
        } catch (Exception e) {
            oficio.setReu("");
        }
        try {
//            oficio.setEnvolvido(txtEnvolvido.getText());
        } catch (Exception e) {
  //          oficio.setEnvolvido("");
        }
        try {
    //        oficio.setAbc(txtAbc.getText());
        } catch (Exception e) {
      //      oficio.setAbc("");
        }
        try {
            oficio.setData(txtData.getText());
        } catch (Exception e) {
            oficio.setData("");
        }
        //  JOptionPane.showMessageDialog(txtOficio,"Dentro do form" +  txtOficio.getText());     
        GeraOficioxxxx GO = new GeraOficioxxxx();
//  teste2 Gd = new teste2();
        if ("".equals(txtOficio.getText())) {
            JOptionPane.showMessageDialog(txtOficio, "Favor digitar o número do Ofício");
        } else {
            if ("ABC".equals(txtAbc.getText())) {
                JOptionPane.showMessageDialog(txtAbc, "Favor digitar as iniciais do seu nome");
            } else {
                if ("".equals(txtCorpo.getText())) {
                    JOptionPane.showMessageDialog(txtCorpo, "Favor digitar a resposta");
                } else {
                    if ("".equals(txtEndereco.getText())) {
                        JOptionPane.showMessageDialog(txtEndereco, "Favor digitar o endereço");
                    } else {
                        try {
                            GO.Gerar(oficio);
                            //  GO.colocaLogo();
                        } catch (IOException | DocumentException | InterruptedException ex) {
                            Logger.getLogger(FrmPrincipalTeste.class.getName()).log(Level.SEVERE, null, ex);                        }
                        // Salvar na rede
                        try {
                            PdfReader pdfComLogo = new PdfReader("c:\\temp\\OficioComLogo.pdf");
                            //--   PdfReader pdfComLogo = new PdfReader("OficioComLogo.pdf");
                            int number_of_pages = pdfComLogo.getNumberOfPages();
                            //  PdfStamper stamp = new PdfStamper(pdfComLogo, new FileOutputStream("c:\\temp\\OficioComLogo.pdf"));
                            LocalDate hoje = new LocalDate();//hoje
                            System.out.println(hoje + "dentro");
                            PdfStamper stamp;
                            if (!"aaa".equals(oficio.getAbc())) {//Usar aaa nas inicias para não gravar na pasta--testar o programa                         

                                try {
                                    //stamp = new PdfStamper(pdfComLogo, new FileOutputStream("G:\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\Oficio_"+Oficio+"_"+hoje+"_"+Abc+".pdf"));
                                    stamp = new PdfStamper(pdfComLogo, new FileOutputStream("G:\\FUNCI\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\Oficio_" + oficio.getOficio() + "_" + hoje + "_" + System.getProperty("user.name").toUpperCase() + ".pdf"));

                                } catch (DocumentException | IOException e) {
                                    stamp = new PdfStamper(pdfComLogo, new FileOutputStream("G:\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\Oficio_" + oficio.getOficio() + "_" + hoje + "_" + System.getProperty("user.name").toUpperCase() + ".pdf"));
                                    //   stamp = new PdfStamper(pdfComLogo, new FileOutputStream("G:\\FUNCI\\Publica\\INFORMACOES A TERCEIROS\\OFÍCIO\\OFICIO_PROG\\Oficio_"+Oficio+"_"+hoje+"_"+Abc+".pdf"));
                              }
                                stamp.close();
                                pdfComLogo.close();
                            }
                        } catch (DocumentException | IOException i1) {
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnOficioActionPerformed

    private void btnARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnARActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        Oficio oficio = new Oficio();

        oficio.setOficio(txtOficio.getText());
     //   oficio.setAof(txtAOF.getText());
        oficio.setProcesso(txtProcesso.getText());
        oficio.setCorpo(txtCorpo.getText());
        oficio.setDestinario(txtDestinatário.getText());
        oficio.setEndereco(txtEndereco.getText());
   //     oficio.setAbc(txtAOF.getText());
       // oficio.setLinhas(txtLinhas.getText());
        GeraOficioxxxx Ga = new GeraOficioxxxx();

        if ("".equals(txtEndereco.getText())) {
            JOptionPane.showMessageDialog(txtCorpo, "Favor digitar o endereço");
        } else {
            try {
                Ga.GerarAR(oficio);
            } catch (DocumentException | IOException e) {
            }

////             try {
////                Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c/temp", "start", "ARF.pdf"});
////            } catch (IOException e) {
////            }
        }

    }//GEN-LAST:event_btnARActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtOficio.setText("");
        txtAbc.setText("ABC");
        txtAutor.setText("");
        txtAOF.setText("");
        txtProcesso.setText("");
        txtReu.setText("");
        txtDestinatário.setText("");
        txtOficioN.setText("");
        txtEnvolvido.setText("");
        txtCorpo.setText("");
        txtDestinatário.setText("");
        txtEndereco.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtAOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAOFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAOFActionPerformed

    private void txtEnvolvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnvolvidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnvolvidoActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtDestinatárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinatárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinatárioActionPerformed

    private void txtInquerito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInquerito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInquerito1ActionPerformed

    private void txtReuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReuActionPerformed

    private void txtLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinhasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FrmPrincipalTeste().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmPrincipalTeste.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FrmPrincipalTeste.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAR;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JButton btnOficio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtAOF;
    private javax.swing.JTextField txtAbc;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextPane txtCorpo;
    private javax.swing.JLabel txtData;
    private javax.swing.JTextField txtDestinatário;
    private javax.swing.JTextPane txtEndereco;
    private javax.swing.JTextField txtEnvolvido;
    private javax.swing.JTextField txtInquerito1;
    private javax.swing.JTextField txtLinhas;
    private javax.swing.JTextField txtOficio;
    private javax.swing.JTextField txtOficioN;
    private javax.swing.JTextField txtProcesso;
    private javax.swing.JTextField txtReu;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
