/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import com.itextpdf.text.DocumentException;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextPane;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDate;
import pdf.GeraOficioxxxx;
import pdf.Oficio;

/**
 *
 * @author f7057419
 */
public final class frmPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal1() {
        
        
         LocalDate hoje = new LocalDate();//hoje
        
       
              Integer mes;
        String mesExtenso = null;
        
        initComponents();
        
              
        
        setBounds(500, 100, 1000, 800);        
        Color corDoformulario = new Color(240, 240, 240);
        getContentPane().setBackground(corDoformulario);
        
       

        //tratamento mês por extenso
        mes = hoje.getMonthOfYear();

        switch (mes) {
            case 1:
                mesExtenso = "Janeiro";
                break;
            case 2:
                mesExtenso = "Fevereiro";
                break;
            case 3:
                mesExtenso = "Março";
                break;
            case 4:
                mesExtenso = "Abril";
                break;
            case 5:
                mesExtenso = "Maio";
                break;
            case 6:
                mesExtenso = "Junho";
                break;
            case 7:
                mesExtenso = "Julho";
                break;
            case 8:
                mesExtenso = "Agosto";
                break;
            case 9:
                mesExtenso = "Setembro";
                break;
            case 10:
                mesExtenso = "Outubro";
                break;
            case 11:
                mesExtenso = "Novembro";
                break;
            case 12:
                mesExtenso = "Dezembro";
                break;
        }     
        txtData.setText("São Paulo, " + hoje.getDayOfMonth() + " de " + mesExtenso + " de " + hoje.getYear()); 
  
        
        fechaApos6Horas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtOficio = new javax.swing.JFormattedTextField();
        try{ 
 javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("201#/########"); 
 txtOficio = new javax.swing.JFormattedTextField(cpf); 
 } 
 catch (Exception e){ 
 }
        jLabel11 = new javax.swing.JLabel();
        txtAOF = new javax.swing.JFormattedTextField();
        try{ 
 javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("201#/#####"); 
 txtAOF = new javax.swing.JFormattedTextField(cpf); 
 } 
 catch (Exception e){ 
 }
        txtData = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProcesso = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCorpo = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDestinatário = new javax.swing.JTextPane();
        txtAbc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        btnOficio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("OFICIO CENOP SJ N.º ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(534, 36, 160, 17);

        txtOficio.setText("2014/14551687");
        txtOficio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOficioActionPerformed(evt);
            }
        });
        jPanel1.add(txtOficio);
        txtOficio.setBounds(704, 36, 260, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("AOF");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(654, 86, 34, 14);

        txtAOF.setText("2014/10120");
        txtAOF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtAOF);
        txtAOF.setBounds(704, 76, 260, 30);

        txtData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtData.setText("São Paulo, 22 de xxxxx de xxxx");
        txtData.setToolTipText("");
        jPanel1.add(txtData);
        txtData.setBounds(614, 126, 350, 22);

        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(854, 546, 110, 40);

        txtProcesso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtProcesso.setText("Processo Nº\t: 0004853-70.2013.8.26.0269\t\t\nClasse–Assunto: Alimentos – Lei Especial nº 5.478/68 - Revisão\nAutor\t: Agnaldo Terra Rocha\nRéu\t: Paloma Martins Rocha e outros\n\n");
        jScrollPane2.setViewportView(txtProcesso);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 205, 870, 216);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Digite os dados do Processo:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 60, 350, 70);

        jTabbedPane1.addTab("     Processo     ", new javax.swing.ImageIcon(getClass().getResource("/telas/processoMenor.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Digite o Ofício:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtCorpo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCorpo.setText("Meritíssimo Juiz,     \t\n  \t\n\tEm atendimento à requisição de Vossa Excelência, por meio do ofício expedido nos autos do processo em \nepígrafe, informamos que Agnaldo Terra Rocha, CPF 247.687.258-05, não possui cartão de crédito VISA ou \nMASTERCARD nesta instituição.\n    \tAs informações contidas neste ofício são confidenciais e estão sendo encaminhadas à Autoridade \ncompetente e requisitante com o devido amparo da Lei Complementar nº 105, de 10 de janeiro de 2001, que dispõe \nsobre o sigilo das operações e serviços prestados pelas Instituições Financeiras.\n  \tColocamo-nos à disposição para eventuais  esclarecimentos e informações porventura necessários, \naproveitando o ensejo para enviar protestos de elevada estima e consideração.\n\nRespeitosamente,");
        jScrollPane3.setViewportView(txtCorpo);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 660, 510));

        jTabbedPane1.addTab("     Corpo     ", new javax.swing.ImageIcon(getClass().getResource("/telas/corpoMenor.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setLayout(null);

        txtDestinatário.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDestinatário.setText("Ao Excelentíssimo Dr.: ");
        jScrollPane1.setViewportView(txtDestinatário);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 900, 30);

        txtAbc.setForeground(new java.awt.Color(51, 51, 255));
        txtAbc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbc.setText("ABC");
        txtAbc.setToolTipText("");
        txtAbc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbcActionPerformed(evt);
            }
        });
        jPanel3.add(txtAbc);
        txtAbc.setBounds(710, 550, 50, 18);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Digite o Endereço:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 20, 360, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("Digite as iniciaios do seu nome-->:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(390, 550, 320, 22);

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEndereco.setText("Trazibulo José Ferreira da Silva \nTribunal de Justiça do Estado de São Paulo  \n1ª Vara da Família e das Sucessões – Comarca de Itapetininga \n Rua Carlos Cardoso, s/n – Jardim Mesquita \nCEP 18213-540 – Itapetininga/SP ");
        jScrollPane4.setViewportView(txtEndereco);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(10, 170, 900, 270);

        jTabbedPane1.addTab("     Destinatário     ", new javax.swing.ImageIcon(getClass().getResource("/telas/destinatarioMenor.png")), jPanel3); // NOI18N

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOficio.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnOficio.setText("OFICIO");
        btnOficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficioActionPerformed(evt);
            }
        });
        jPanel4.add(btnOficio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 400, 190));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setText("AR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 190, 140));

        jTabbedPane1.addTab("     Ofício     ", new javax.swing.ImageIcon(getClass().getResource("/telas/oficioMenor.png")), jPanel4); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 970, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/bb_logo1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/nome.png"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 370, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/desenvolvido.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, 280, 30));

        jButton2.setText("Formulário 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtOficio.setText("");
        //txtAutor.setText("");
        //txtClasse.setText("");
        txtAOF.setText("");
        txtProcesso.setText("");
      //  txtReu.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtAbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbcActionPerformed

    private void txtOficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOficioActionPerformed

    private void btnOficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficioActionPerformed
    // TODO add your handling code here:
    //    GeraOficioxxxx G = new GeraOficioxxxx();
        
        
        
        Oficio oficio = new Oficio();
        
        
        
        oficio.setOficio(txtOficio.getText());       
//        oficio.setAof(txtAOF.getText());
        oficio.setProcesso(txtProcesso.getText());
        oficio.setCorpo(txtCorpo.getText());
        oficio.setDestinario(txtDestinatário.getText());
         oficio.setEndereco(txtEndereco.getText());
//        oficio.setAbc(txtAbc.getText());
        oficio.setData(txtData.getText());
        
        String teste;
        teste=oficio.getCorpo();
        
        
 //    JOptionPane.showMessageDialog(txtCorpo, teste, teste, WIDTH);
                
      GeraOficioxxxx GO = new GeraOficioxxxx(); 
   
      
    //  teste2 Gd = new teste2();
      
           
        try {
         GO.Gerar(oficio);           
            
        } catch (DocumentException | IOException e) {
            
          //JOptionPane.showMessageDialog(txtCorpo, e);            
        } catch (InterruptedException ex) {
            Logger.getLogger(frmPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        
        try {                      
                   //    Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "\\temp\\OficioComLogo.pdf"});  
                           Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "OficioComLogo.pdf"});

        } catch (IOException e) {
        }
        
        
        
       
        
        
        
      
                   
        
    }//GEN-LAST:event_btnOficioActionPerformed

    
    public void fechaApos6Horas(){
           new Thread() {
               @Override 
               public void run() { 
                    
                    DateTime dateTime1 = new DateTime();
                    System.out.println(dateTime1.getMinuteOfDay());                   
                   
                 //  DateTime dateTime2 = dateTime1.plusHours(1); 
                   DateTime dateTime2 = dateTime1.plusMinutes(360); 
                   
                   System.out.println(dateTime2.getMinuteOfDay());
                   
                   while ( (dateTime1.getMinuteOfDay()) != (dateTime2.getMinuteOfDay())) {                       
                       dateTime1 = new DateTime();               
                              
                   }                   
                   
                   System.exit(0);                  

               }    
       }.start();
                   }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
          // TODO add your handling code here:
        
        Oficio oficio = new Oficio();
        
        oficio.setOficio(txtOficio.getText());       
     //   oficio.setAof(txtAOF.getText());
        oficio.setProcesso(txtProcesso.getText());
        oficio.setCorpo(txtCorpo.getText());
        oficio.setDestinario(txtDestinatário.getText());
        oficio.setEndereco(txtEndereco.getText());
     //   oficio.setAbc(txtAOF.getText());      
        
        GeraOficioxxxx Ga= new GeraOficioxxxx();
        
        try {          
            Ga.GerarAR(oficio);
        } catch (DocumentException | IOException e) {
        }
        
         try {
          //  Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", "start", "\\temp\\ARF.pdf"}); 
            Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", "start", "ARF.pdf"});
        } catch (IOException e) {
        }
  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmFilho2 = null;      
        try {
            frmFilho2 = new FrmPrincipal();
        } catch (Exception ex) {
            Logger.getLogger(frmPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmFilho2.show();
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOficio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField txtAOF;
    private javax.swing.JTextField txtAbc;
    private javax.swing.JTextPane txtCorpo;
    private javax.swing.JLabel txtData;
    private javax.swing.JTextPane txtDestinatário;
    private javax.swing.JTextPane txtEndereco;
    private javax.swing.JFormattedTextField txtOficio;
    private javax.swing.JTextPane txtProcesso;
    // End of variables declaration//GEN-END:variables
}
